name: ci

on:
  push:
    branches:
      - main # or any branch you want to test on push
  pull_request:
    branches:
      - main # runs tests when a PR is created targeting the main branch

jobs:
  test:
    runs-on: python-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests
        run: |
          python -m unittest discover tests  # This will discover and run tests in the 'tests' folder
